# Generated by Django 5.2.17 on 2026-09-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_detail',
            name='delete',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
